/**
 * GENERATED by tools/asset-pipeline/build.ts — do not edit by hand.
 * Run `pnpm assets` after changing manifest.source.ts.
 * All content: CC0-1.0 by Kenney (kenney.nl) — see ASSET_GUIDE.md.
 */

export interface AssetEntry {
  url: string;
  kit: string;
}

export const MODEL_ASSETS = {
  "world/park-entrance": { url: "/assets/models/world-park-entrance.89c3265e.glb", kit: "Kenney_CoasterKit" },
  "path/straight": { url: "/assets/models/path-straight.285213bd.glb", kit: "Kenney_CoasterKit" },
  "path/corner": { url: "/assets/models/path-corner.6d8b5b55.glb", kit: "Kenney_CoasterKit" },
  "path/crossing": { url: "/assets/models/path-crossing.15585dbc.glb", kit: "Kenney_CoasterKit" },
  "path/split": { url: "/assets/models/path-split.2ffe62d0.glb", kit: "Kenney_CoasterKit" },
  "path/end": { url: "/assets/models/path-end.ac924955.glb", kit: "Kenney_CoasterKit" },
  "queue/straight": { url: "/assets/models/queue-straight.218c7dcd.glb", kit: "Kenney_CoasterKit" },
  "queue/corner": { url: "/assets/models/queue-corner.1852bace.glb", kit: "Kenney_CoasterKit" },
  "queue/crossing": { url: "/assets/models/queue-crossing.f48196e2.glb", kit: "Kenney_CoasterKit" },
  "queue/split": { url: "/assets/models/queue-split.2cdf4e44.glb", kit: "Kenney_CoasterKit" },
  "stalls/food": { url: "/assets/models/stalls-food.feab6800.glb", kit: "Kenney_CoasterKit" },
  "stalls/drinks": { url: "/assets/models/stalls-drinks.6efaf944.glb", kit: "Kenney_CoasterKit" },
  "stalls/info": { url: "/assets/models/stalls-info.5a1d5aa2.glb", kit: "Kenney_CoasterKit" },
  "stalls/toilets": { url: "/assets/models/stalls-toilets.40a7a39b.glb", kit: "Kenney_CoasterKit" },
  "furniture/bench": { url: "/assets/models/furniture-bench.8e41f0ed.glb", kit: "Kenney_CoasterKit" },
  "furniture/bin": { url: "/assets/models/furniture-bin.71cacf56.glb", kit: "Kenney_CoasterKit" },
  "furniture/lamp": { url: "/assets/models/furniture-lamp.440b70c7.glb", kit: "Kenney_CityKitRoads" },
  "furniture/flowers": { url: "/assets/models/furniture-flowers.fee5391e.glb", kit: "Kenney_CoasterKit" },
  "furniture/grass-tuft": { url: "/assets/models/furniture-grass-tuft.21b6f28e.glb", kit: "Kenney_CoasterKit" },
  "furniture/flag-red": { url: "/assets/models/furniture-flag-red.cda01992.glb", kit: "Kenney_MinigolfKit" },
  "furniture/flag-blue": { url: "/assets/models/furniture-flag-blue.f9fc2ce2.glb", kit: "Kenney_MinigolfKit" },
  "furniture/sculpture": { url: "/assets/models/furniture-sculpture.8f30fe6e.glb", kit: "Kenney_MinigolfKit" },
  "furniture/column": { url: "/assets/models/furniture-column.a98a0095.glb", kit: "Kenney_NatureKit" },
  "furniture/planter": { url: "/assets/models/furniture-planter.a9eccefc.glb", kit: "Kenney_CityKitSuburban" },
  "furniture/umbrella": { url: "/assets/models/furniture-umbrella.718e633d.glb", kit: "Kenney_CityKitCommercial" },
  "nature/tree-oak": { url: "/assets/models/nature-tree-oak.d1d384de.glb", kit: "Kenney_NatureKit" },
  "nature/tree-oak-dark": { url: "/assets/models/nature-tree-oak-dark.94ad1b6e.glb", kit: "Kenney_NatureKit" },
  "nature/tree-detailed": { url: "/assets/models/nature-tree-detailed.f7801a97.glb", kit: "Kenney_NatureKit" },
  "nature/tree-pine": { url: "/assets/models/nature-tree-pine.89521c62.glb", kit: "Kenney_NatureKit" },
  "nature/tree-pine-tall": { url: "/assets/models/nature-tree-pine-tall.c526d200.glb", kit: "Kenney_NatureKit" },
  "nature/tree-palm": { url: "/assets/models/nature-tree-palm.c0653e7f.glb", kit: "Kenney_NatureKit" },
  "nature/tree-palm-bend": { url: "/assets/models/nature-tree-palm-bend.28a23a2e.glb", kit: "Kenney_NatureKit" },
  "nature/bush": { url: "/assets/models/nature-bush.139f0adb.glb", kit: "Kenney_NatureKit" },
  "nature/bush-trimmed": { url: "/assets/models/nature-bush-trimmed.236985e1.glb", kit: "Kenney_NatureKit" },
  "nature/hedge": { url: "/assets/models/nature-hedge.e580d785.glb", kit: "Kenney_NatureKit" },
  "nature/flower-red": { url: "/assets/models/nature-flower-red.73cfc8d6.glb", kit: "Kenney_NatureKit" },
  "nature/flower-yellow": { url: "/assets/models/nature-flower-yellow.c9054d49.glb", kit: "Kenney_NatureKit" },
  "nature/mushroom-red": { url: "/assets/models/nature-mushroom-red.2af01061.glb", kit: "Kenney_NatureKit" },
  "nature/rock-small": { url: "/assets/models/nature-rock-small.e6afaae1.glb", kit: "Kenney_NatureKit" },
  "nature/rock-large": { url: "/assets/models/nature-rock-large.bf8994d0.glb", kit: "Kenney_NatureKit" },
  "nature/rock-formation": { url: "/assets/models/nature-rock-formation.f5757151.glb", kit: "Kenney_NatureKit" },
  "nature/stump": { url: "/assets/models/nature-stump.39f8dbc7.glb", kit: "Kenney_NatureKit" },
  "nature/log": { url: "/assets/models/nature-log.ee14c986.glb", kit: "Kenney_NatureKit" },
  "nature/monument-ring": { url: "/assets/models/nature-monument-ring.e448c8c6.glb", kit: "Kenney_NatureKit" },
  "nature/obelisk": { url: "/assets/models/nature-obelisk.435f2ab2.glb", kit: "Kenney_NatureKit" },
  "nature/fence-wood": { url: "/assets/models/nature-fence-wood.d4820dc2.glb", kit: "Kenney_NatureKit" },
  "nature/fence-planks": { url: "/assets/models/nature-fence-planks.e415350c.glb", kit: "Kenney_NatureKit" },
} as const satisfies Record<string, AssetEntry>;

export type ModelAssetId = keyof typeof MODEL_ASSETS;

export const SKY_ASSETS = {
  "sky/morning": { url: "/assets/sky/sky-morning.7b445e95.png", kit: "Kenney_Skyboxes" },
  "sky/day": { url: "/assets/sky/sky-day.b7d98fe9.png", kit: "Kenney_Skyboxes" },
  "sky/night": { url: "/assets/sky/sky-night.2276d9e1.png", kit: "Kenney_Skyboxes" },
} as const satisfies Record<string, AssetEntry>;

export type SkyAssetId = keyof typeof SKY_ASSETS;

/** Source kits shipped in this build (feeds the credits screen). */
export const CREDIT_KITS: readonly string[] = [
  "Kenney_CityKitCommercial",
  "Kenney_CityKitRoads",
  "Kenney_CityKitSuburban",
  "Kenney_CoasterKit",
  "Kenney_MinigolfKit",
  "Kenney_NatureKit",
  "Kenney_Skyboxes"
];

export function modelUrl(id: ModelAssetId): string {
  return MODEL_ASSETS[id].url;
}

export function skyUrl(id: SkyAssetId): string {
  return SKY_ASSETS[id].url;
}
