/**
 * GENERATED by tools/asset-pipeline/build.ts — do not edit by hand.
 * Run `pnpm assets` after changing manifest.source.ts.
 * All content: CC0-1.0 by Kenney (kenney.nl) — see ASSET_GUIDE.md.
 */

export interface AssetEntry {
  url: string;
  kit: string;
}

export const MODEL_ASSETS = {
  "world/park-entrance": { url: "/assets/models/world-park-entrance.89c3265e.glb", kit: "Kenney_CoasterKit" },
  "path/straight": { url: "/assets/models/path-straight.285213bd.glb", kit: "Kenney_CoasterKit" },
  "path/corner": { url: "/assets/models/path-corner.6d8b5b55.glb", kit: "Kenney_CoasterKit" },
  "path/crossing": { url: "/assets/models/path-crossing.15585dbc.glb", kit: "Kenney_CoasterKit" },
  "path/split": { url: "/assets/models/path-split.2ffe62d0.glb", kit: "Kenney_CoasterKit" },
  "path/end": { url: "/assets/models/path-end.ac924955.glb", kit: "Kenney_CoasterKit" },
  "queue/straight": { url: "/assets/models/queue-straight.218c7dcd.glb", kit: "Kenney_CoasterKit" },
  "queue/corner": { url: "/assets/models/queue-corner.1852bace.glb", kit: "Kenney_CoasterKit" },
  "queue/crossing": { url: "/assets/models/queue-crossing.f48196e2.glb", kit: "Kenney_CoasterKit" },
  "queue/split": { url: "/assets/models/queue-split.2cdf4e44.glb", kit: "Kenney_CoasterKit" },
  "stalls/food": { url: "/assets/models/stalls-food.feab6800.glb", kit: "Kenney_CoasterKit" },
  "stalls/drinks": { url: "/assets/models/stalls-drinks.6efaf944.glb", kit: "Kenney_CoasterKit" },
  "stalls/info": { url: "/assets/models/stalls-info.5a1d5aa2.glb", kit: "Kenney_CoasterKit" },
  "stalls/toilets": { url: "/assets/models/stalls-toilets.40a7a39b.glb", kit: "Kenney_CoasterKit" },
  "furniture/bench": { url: "/assets/models/furniture-bench.8e41f0ed.glb", kit: "Kenney_CoasterKit" },
  "furniture/bin": { url: "/assets/models/furniture-bin.71cacf56.glb", kit: "Kenney_CoasterKit" },
  "furniture/lamp": { url: "/assets/models/furniture-lamp.17884ea4.glb", kit: "Kenney_CityKitRoads" },
  "furniture/flowers": { url: "/assets/models/furniture-flowers.fee5391e.glb", kit: "Kenney_CoasterKit" },
  "furniture/grass-tuft": { url: "/assets/models/furniture-grass-tuft.21b6f28e.glb", kit: "Kenney_CoasterKit" },
  "furniture/flag-red": { url: "/assets/models/furniture-flag-red.52112ef2.glb", kit: "Kenney_MinigolfKit" },
  "furniture/flag-blue": { url: "/assets/models/furniture-flag-blue.d345bfd2.glb", kit: "Kenney_MinigolfKit" },
  "furniture/sculpture": { url: "/assets/models/furniture-sculpture.8f30fe6e.glb", kit: "Kenney_MinigolfKit" },
  "furniture/column": { url: "/assets/models/furniture-column.4bc285a3.glb", kit: "Kenney_NatureKit" },
  "furniture/planter": { url: "/assets/models/furniture-planter.a9eccefc.glb", kit: "Kenney_CityKitSuburban" },
  "furniture/umbrella": { url: "/assets/models/furniture-umbrella.718e633d.glb", kit: "Kenney_CityKitCommercial" },
  "nature/tree-oak": { url: "/assets/models/nature-tree-oak.152a0841.glb", kit: "Kenney_NatureKit" },
  "nature/tree-oak-dark": { url: "/assets/models/nature-tree-oak-dark.58ca0848.glb", kit: "Kenney_NatureKit" },
  "nature/tree-detailed": { url: "/assets/models/nature-tree-detailed.a5988778.glb", kit: "Kenney_NatureKit" },
  "nature/tree-pine": { url: "/assets/models/nature-tree-pine.79e0bc43.glb", kit: "Kenney_NatureKit" },
  "nature/tree-pine-tall": { url: "/assets/models/nature-tree-pine-tall.d653712c.glb", kit: "Kenney_NatureKit" },
  "nature/tree-palm": { url: "/assets/models/nature-tree-palm.d04e081e.glb", kit: "Kenney_NatureKit" },
  "nature/tree-palm-bend": { url: "/assets/models/nature-tree-palm-bend.f3c3be49.glb", kit: "Kenney_NatureKit" },
  "nature/bush": { url: "/assets/models/nature-bush.fa8cca26.glb", kit: "Kenney_NatureKit" },
  "nature/bush-trimmed": { url: "/assets/models/nature-bush-trimmed.fe831af9.glb", kit: "Kenney_NatureKit" },
  "nature/hedge": { url: "/assets/models/nature-hedge.95d2f840.glb", kit: "Kenney_NatureKit" },
  "nature/flower-red": { url: "/assets/models/nature-flower-red.73cfc8d6.glb", kit: "Kenney_NatureKit" },
  "nature/flower-yellow": { url: "/assets/models/nature-flower-yellow.c9054d49.glb", kit: "Kenney_NatureKit" },
  "nature/mushroom-red": { url: "/assets/models/nature-mushroom-red.2af01061.glb", kit: "Kenney_NatureKit" },
  "nature/rock-small": { url: "/assets/models/nature-rock-small.e6afaae1.glb", kit: "Kenney_NatureKit" },
  "nature/rock-large": { url: "/assets/models/nature-rock-large.6bb89788.glb", kit: "Kenney_NatureKit" },
  "nature/rock-formation": { url: "/assets/models/nature-rock-formation.919721c8.glb", kit: "Kenney_NatureKit" },
  "nature/stump": { url: "/assets/models/nature-stump.39f8dbc7.glb", kit: "Kenney_NatureKit" },
  "nature/log": { url: "/assets/models/nature-log.ee14c986.glb", kit: "Kenney_NatureKit" },
  "nature/monument-ring": { url: "/assets/models/nature-monument-ring.74968676.glb", kit: "Kenney_NatureKit" },
  "nature/obelisk": { url: "/assets/models/nature-obelisk.e8411d66.glb", kit: "Kenney_NatureKit" },
  "nature/fence-wood": { url: "/assets/models/nature-fence-wood.0652f90e.glb", kit: "Kenney_NatureKit" },
  "nature/fence-planks": { url: "/assets/models/nature-fence-planks.dd1c6c83.glb", kit: "Kenney_NatureKit" },
  "guests/char-a": { url: "/assets/models/guests-char-a.32b890bc.glb", kit: "Kenney_BlockyCharacters" },
  "guests/char-b": { url: "/assets/models/guests-char-b.46396c8b.glb", kit: "Kenney_BlockyCharacters" },
  "guests/char-c": { url: "/assets/models/guests-char-c.d35d5c2f.glb", kit: "Kenney_BlockyCharacters" },
  "guests/char-d": { url: "/assets/models/guests-char-d.6603c643.glb", kit: "Kenney_BlockyCharacters" },
  "theme/pirate-palm": { url: "/assets/models/theme-pirate-palm.acae4ebb.glb", kit: "Kenney_PirateKit" },
  "theme/pirate-palm-bend": { url: "/assets/models/theme-pirate-palm-bend.935a438a.glb", kit: "Kenney_PirateKit" },
  "theme/pirate-flag": { url: "/assets/models/theme-pirate-flag.80cac0ba.glb", kit: "Kenney_PirateKit" },
  "theme/pirate-crate": { url: "/assets/models/theme-pirate-crate.5271d8e3.glb", kit: "Kenney_PirateKit" },
  "theme/pirate-cannon": { url: "/assets/models/theme-pirate-cannon.c5ae6ad4.glb", kit: "Kenney_PirateKit" },
  "theme/pirate-chest": { url: "/assets/models/theme-pirate-chest.c64f744a.glb", kit: "Kenney_PirateKit" },
  "theme/pirate-tower": { url: "/assets/models/theme-pirate-tower.876bea2a.glb", kit: "Kenney_PirateKit" },
  "theme/pirate-rocks": { url: "/assets/models/theme-pirate-rocks.5754b50e.glb", kit: "Kenney_PirateKit" },
  "theme/space-rocket": { url: "/assets/models/theme-space-rocket.5bea3675.glb", kit: "Kenney_SpaceKit" },
  "theme/space-dish": { url: "/assets/models/theme-space-dish.70b719bd.glb", kit: "Kenney_SpaceKit" },
  "theme/space-speeder": { url: "/assets/models/theme-space-speeder.161257cb.glb", kit: "Kenney_SpaceKit" },
  "theme/space-meteor": { url: "/assets/models/theme-space-meteor.34c5501a.glb", kit: "Kenney_SpaceKit" },
  "theme/space-astronaut": { url: "/assets/models/theme-space-astronaut.080dde30.glb", kit: "Kenney_SpaceKit" },
  "theme/space-alien": { url: "/assets/models/theme-space-alien.740a6a1a.glb", kit: "Kenney_SpaceKit" },
  "theme/space-generator": { url: "/assets/models/theme-space-generator.562cf135.glb", kit: "Kenney_SpaceKit" },
  "theme/castle-flag": { url: "/assets/models/theme-castle-flag.42c3b237.glb", kit: "Kenney_CastleKit" },
  "theme/castle-banner": { url: "/assets/models/theme-castle-banner.77c6be15.glb", kit: "Kenney_CastleKit" },
  "theme/castle-catapult": { url: "/assets/models/theme-castle-catapult.5a888cbc.glb", kit: "Kenney_CastleKit" },
  "theme/castle-tower": { url: "/assets/models/theme-castle-tower.4294621d.glb", kit: "Kenney_CastleKit" },
  "theme/castle-stairs": { url: "/assets/models/theme-castle-stairs.8b985687.glb", kit: "Kenney_CastleKit" },
  "theme/castle-rocks": { url: "/assets/models/theme-castle-rocks.097d64dc.glb", kit: "Kenney_CastleKit" },
  "theme/spooky-gravestone": { url: "/assets/models/theme-spooky-gravestone.96161041.glb", kit: "Kenney_GraveyardKit" },
  "theme/spooky-cross": { url: "/assets/models/theme-spooky-cross.9690a747.glb", kit: "Kenney_GraveyardKit" },
  "theme/spooky-crypt": { url: "/assets/models/theme-spooky-crypt.11041b84.glb", kit: "Kenney_GraveyardKit" },
  "theme/spooky-coffin": { url: "/assets/models/theme-spooky-coffin.7a189f14.glb", kit: "Kenney_GraveyardKit" },
  "theme/spooky-candles": { url: "/assets/models/theme-spooky-candles.453180e1.glb", kit: "Kenney_GraveyardKit" },
  "theme/spooky-altar": { url: "/assets/models/theme-spooky-altar.3410617b.glb", kit: "Kenney_GraveyardKit" },
  "theme/spooky-brazier": { url: "/assets/models/theme-spooky-brazier.2d549bf2.glb", kit: "Kenney_GraveyardKit" },
  "theme/spooky-pumpkin": { url: "/assets/models/theme-spooky-pumpkin.77dc4025.glb", kit: "Kenney_GraveyardKit" },
  "theme/winter-snowman": { url: "/assets/models/theme-winter-snowman.fb1db3d3.glb", kit: "Kenney_HolidayKit" },
  "theme/winter-cane-red": { url: "/assets/models/theme-winter-cane-red.2f4cf29b.glb", kit: "Kenney_HolidayKit" },
  "theme/winter-cane-green": { url: "/assets/models/theme-winter-cane-green.834681b4.glb", kit: "Kenney_HolidayKit" },
  "theme/winter-present": { url: "/assets/models/theme-winter-present.5f1e6edf.glb", kit: "Kenney_HolidayKit" },
  "theme/winter-reindeer": { url: "/assets/models/theme-winter-reindeer.fb56102f.glb", kit: "Kenney_HolidayKit" },
  "theme/winter-sled": { url: "/assets/models/theme-winter-sled.4fe7178b.glb", kit: "Kenney_HolidayKit" },
  "theme/winter-snowpile": { url: "/assets/models/theme-winter-snowpile.9c82bb95.glb", kit: "Kenney_HolidayKit" },
  "theme/winter-nutcracker": { url: "/assets/models/theme-winter-nutcracker.4e6af0b2.glb", kit: "Kenney_HolidayKit" },
  "theme/winter-tree": { url: "/assets/models/theme-winter-tree.07f73549.glb", kit: "Kenney_HolidayKit" },
  "staff/janitor": { url: "/assets/models/staff-janitor.09918fe3.glb", kit: "Kenney_BlockyCharacters" },
  "staff/mechanic": { url: "/assets/models/staff-mechanic.8f50aee5.glb", kit: "Kenney_BlockyCharacters" },
  "staff/entertainer": { url: "/assets/models/staff-entertainer.6864b9db.glb", kit: "Kenney_BlockyCharacters" },
  "coaster/station": { url: "/assets/models/coaster-station.f5aa45d0.glb", kit: "Kenney_CoasterKit" },
  "coaster/station-gate": { url: "/assets/models/coaster-station-gate.03e8f4f9.glb", kit: "Kenney_CoasterKit" },
  "coaster/support": { url: "/assets/models/coaster-support.de10aa2f.glb", kit: "Kenney_CoasterKit" },
  "coaster/mouse-track": { url: "/assets/models/coaster-mouse-track.09cb3cbd.glb", kit: "Kenney_CoasterKit" },
  "coaster/mouse-corner": { url: "/assets/models/coaster-mouse-corner.9386340f.glb", kit: "Kenney_CoasterKit" },
  "coaster/mouse-slope": { url: "/assets/models/coaster-mouse-slope.90ee6eed.glb", kit: "Kenney_CoasterKit" },
  "coaster/mouse-loop": { url: "/assets/models/coaster-mouse-loop.5ec891d6.glb", kit: "Kenney_CoasterKit" },
  "coaster/flume-track": { url: "/assets/models/coaster-flume-track.7f7d26eb.glb", kit: "Kenney_CoasterKit" },
  "coaster/flume-corner": { url: "/assets/models/coaster-flume-corner.f726ac2d.glb", kit: "Kenney_CoasterKit" },
  "coaster/flume-slope": { url: "/assets/models/coaster-flume-slope.36c6b1bf.glb", kit: "Kenney_CoasterKit" },
  "coaster/flume-loop": { url: "/assets/models/coaster-flume-loop.da5cc9c6.glb", kit: "Kenney_CoasterKit" },
  "coaster/train-front": { url: "/assets/models/coaster-train-front.e2f2bc04.glb", kit: "Kenney_CoasterKit" },
  "coaster/train-car": { url: "/assets/models/coaster-train-car.8072783a.glb", kit: "Kenney_CoasterKit" },
  "coaster/train-log": { url: "/assets/models/coaster-train-log.9ce4e2e2.glb", kit: "Kenney_CoasterKit" },
  "coaster/steel-track": { url: "/assets/models/coaster-steel-track.0fed9282.glb", kit: "Kenney_CoasterKit" },
  "coaster/steel-corner": { url: "/assets/models/coaster-steel-corner.b282fd15.glb", kit: "Kenney_CoasterKit" },
  "coaster/steel-slope": { url: "/assets/models/coaster-steel-slope.070890aa.glb", kit: "Kenney_CoasterKit" },
  "coaster/steel-loop": { url: "/assets/models/coaster-steel-loop.5aa955fc.glb", kit: "Kenney_CoasterKit" },
  "coaster/hanging-track": { url: "/assets/models/coaster-hanging-track.ace2b831.glb", kit: "Kenney_CoasterKit" },
  "coaster/hanging-corner": { url: "/assets/models/coaster-hanging-corner.2f88c696.glb", kit: "Kenney_CoasterKit" },
  "coaster/hanging-slope": { url: "/assets/models/coaster-hanging-slope.b5eb5ad1.glb", kit: "Kenney_CoasterKit" },
  "coaster/hanging-loop": { url: "/assets/models/coaster-hanging-loop.745a10bc.glb", kit: "Kenney_CoasterKit" },
  "coaster/monorail-track": { url: "/assets/models/coaster-monorail-track.01ea53a8.glb", kit: "Kenney_CoasterKit" },
  "coaster/monorail-corner": { url: "/assets/models/coaster-monorail-corner.b1e2b24b.glb", kit: "Kenney_CoasterKit" },
  "coaster/monorail-slope": { url: "/assets/models/coaster-monorail-slope.ed6cd539.glb", kit: "Kenney_CoasterKit" },
  "coaster/monorail-loop": { url: "/assets/models/coaster-monorail-loop.d28115fb.glb", kit: "Kenney_CoasterKit" },
  "coaster/train-steel": { url: "/assets/models/coaster-train-steel.3c1490a2.glb", kit: "Kenney_CoasterKit" },
  "coaster/train-hanging": { url: "/assets/models/coaster-train-hanging.8cda41f9.glb", kit: "Kenney_CoasterKit" },
  "coaster/train-monorail": { url: "/assets/models/coaster-train-monorail.f0bf7a80.glb", kit: "Kenney_CoasterKit" },
  "rides/pirate-ship": { url: "/assets/models/rides-pirate-ship.70dc3835.glb", kit: "Kenney_PirateKit" },
  "rides/bumper-car-a": { url: "/assets/models/rides-bumper-car-a.ed5855c5.glb", kit: "Kenney_ToyCarKit" },
  "rides/bumper-car-b": { url: "/assets/models/rides-bumper-car-b.68d260e7.glb", kit: "Kenney_ToyCarKit" },
  "rides/bumper-car-c": { url: "/assets/models/rides-bumper-car-c.070c2672.glb", kit: "Kenney_ToyCarKit" },
} as const satisfies Record<string, AssetEntry>;

export type ModelAssetId = keyof typeof MODEL_ASSETS;

export const SKY_ASSETS = {
  "sky/morning": { url: "/assets/sky/sky-morning.7b445e95.png", kit: "Kenney_Skyboxes" },
  "sky/day": { url: "/assets/sky/sky-day.b7d98fe9.png", kit: "Kenney_Skyboxes" },
  "sky/night": { url: "/assets/sky/sky-night.2276d9e1.png", kit: "Kenney_Skyboxes" },
} as const satisfies Record<string, AssetEntry>;

export type SkyAssetId = keyof typeof SKY_ASSETS;

export const SPRITE_ASSETS = {
  "emote/happy": { url: "/assets/sprites/emote-happy.01bacb8e.png", kit: "Kenney_EmotesPack" },
  "emote/star": { url: "/assets/sprites/emote-star.41e22f49.png", kit: "Kenney_EmotesPack" },
  "emote/heart": { url: "/assets/sprites/emote-heart.9a71a696.png", kit: "Kenney_EmotesPack" },
  "emote/hungry": { url: "/assets/sprites/emote-hungry.791c39d0.png", kit: "Kenney_EmotesPack" },
  "emote/thirsty": { url: "/assets/sprites/emote-thirsty.a6253d1c.png", kit: "Kenney_EmotesPack" },
  "emote/tired": { url: "/assets/sprites/emote-tired.a8152dde.png", kit: "Kenney_EmotesPack" },
  "emote/toilet": { url: "/assets/sprites/emote-toilet.1a1ad3d8.png", kit: "Kenney_EmotesPack" },
  "emote/angry": { url: "/assets/sprites/emote-angry.edcbad27.png", kit: "Kenney_EmotesPack" },
  "emote/expensive": { url: "/assets/sprites/emote-expensive.72b5e7d6.png", kit: "Kenney_EmotesPack" },
  "emote/sad": { url: "/assets/sprites/emote-sad.a0b1b930.png", kit: "Kenney_EmotesPack" },
  "emote/idea": { url: "/assets/sprites/emote-idea.0acfe35b.png", kit: "Kenney_EmotesPack" },
} as const satisfies Record<string, AssetEntry>;

export type SpriteAssetId = keyof typeof SPRITE_ASSETS;

export function spriteUrl(id: SpriteAssetId): string {
  return SPRITE_ASSETS[id].url;
}

/** Source kits shipped in this build (feeds the credits screen). */
export const CREDIT_KITS: readonly string[] = [
  "Kenney_BlockyCharacters",
  "Kenney_CastleKit",
  "Kenney_CityKitCommercial",
  "Kenney_CityKitRoads",
  "Kenney_CityKitSuburban",
  "Kenney_CoasterKit",
  "Kenney_EmotesPack",
  "Kenney_GraveyardKit",
  "Kenney_HolidayKit",
  "Kenney_MinigolfKit",
  "Kenney_NatureKit",
  "Kenney_PirateKit",
  "Kenney_Skyboxes",
  "Kenney_SpaceKit",
  "Kenney_ToyCarKit"
];

export function modelUrl(id: ModelAssetId): string {
  return MODEL_ASSETS[id].url;
}

export function skyUrl(id: SkyAssetId): string {
  return SKY_ASSETS[id].url;
}
